from functools import wraps
from flask import session, redirect, url_for, flash
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
import sqlite3
from io import BytesIO
from reportlab.lib.units import inch

def get_db_connection():
    conn = sqlite3.connect("finance.db")
    conn.row_factory = sqlite3.Row
    return conn


def build_transaction_pdf(transactions, filename, total_income=0, total_expenses=0, balance=0):
    pdf = SimpleDocTemplate(filename, pagesize=letter)
    elements = []
    styles = getSampleStyleSheet()

    # Title
    title_style = ParagraphStyle('TitleStyle', parent=styles['Title'], fontSize=24, alignment=1, spaceAfter=12)
    elements.append(Paragraph("Financial Report", title_style))
    elements.append(Spacer(1, 12))

    # Summary Table
    summary_data = [
        ["Total Income", f"${total_income:.2f}"],
        ["Total Expenses", f"${total_expenses:.2f}"],
        ["Balance", f"${balance:.2f}"]
    ]
    
    summary_table = Table(summary_data, colWidths=[200, 200])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('ALIGN', (0, 0), (0, -1), 'RIGHT'),  # Right-align the amount column
        ('ALIGN', (1, 0), (1, -1), 'RIGHT')
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 24))

    # Transactions Table
    if transactions:
        table_data = [["Date", "Description", "Category", "Type", "Amount"]]
        
        for txn in transactions:
            table_data.append([
                txn.get("date", ""),
                txn.get("description", ""),
                txn.get("category", ""),
                txn.get("type", ""),
                f"${txn.get('amount', 0):.2f}"
            ])
        
        table = Table(table_data, hAlign='LEFT', colWidths=[1.0*inch, 2.0*inch, 1.5*inch, 1.0*inch, 1.0*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.lightblue),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('ALIGN', (4, 1), (4, -1), 'RIGHT')  # Right-align the "Amount" column
        ]))
        elements.append(table)
    else:
        elements.append(Paragraph("No transactions available.", styles['Normal']))

    # Footer with page number
    footer_style = ParagraphStyle(name='footer', fontSize=10, alignment=1, spaceBefore=10, spaceAfter=10)
    elements.append(Spacer(1, 12))
    elements.append(Paragraph("Generated by Financial Tracker", footer_style))

    # Build the PDF
    pdf.build(elements)

def login_required(f):
    """
    Decorate routes to require login.
    """

    @wraps(f)
    def decorated_function(*args, **kwargs):
        if session.get("user_id") is None:
            return redirect("/login")
        return f(*args, **kwargs)

    return decorated_function


def get_transaction_data(user_id):
    conn = sqlite3.connect("finance.db")
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()

    cur.execute(
        "SELECT date, amount, type, category, description FROM transactions WHERE user_id = ? ORDER BY date DESC",
        (user_id,)
    )
    transactions = cur.fetchall()
    conn.close()

    # Convert to list of dicts for PDF helper
    return [dict(txn) for txn in transactions]


def get_transaction_summary(user_id):
    conn = sqlite3.connect("finance.db")
    cur = conn.cursor()

    # Sum of all Income
    cur.execute(
        "SELECT SUM(amount) FROM transactions WHERE user_id=? AND type='income'",
        (user_id,)
    )
    total_income = cur.fetchone()[0] or 0  # if no income, default to 0

    # Sum of all Expenses
    cur.execute(
        "SELECT SUM(amount) FROM transactions WHERE user_id=? AND type='expenses'",
        (user_id,)
    )
    total_expenses = cur.fetchone()[0] or 0

    balance = total_income - total_expenses
    conn.close()

    return total_income, total_expenses, balance


def format_transactions(transactions):
    """Standardize transaction dates to YYYY-MM-DD"""
    transactions = [dict(txn) for txn in transactions]
    for txn in transactions:
        txn["date"] = txn["date"].split(" ")[0]
    return transactions

def get_last_month_expenses(user_id):
    """
    Helper function to get the previous month's total expenses.
    """
    from datetime import datetime, timedelta
    last_month = (datetime.now() - timedelta(days=30)).month
    with get_db_connection() as conn:
        cur = conn.cursor()
        cur.execute("SELECT SUM(amount) FROM transactions WHERE user_id=? AND type='expenses' AND strftime('%m', date) = ?", (user_id, last_month))
        result = cur.fetchone()
    return result[0] if result[0] else 0